const data = {
  products: [
    {
      _id: '1',
      name: 'Juicy Strawberry',
      slug: 'juicy-strawberry',
      category: 'Fruits',
      origin: 'Italy',
      occasion: ['dessert', 'fruit', 'smoothies', 'icecream'],
      price: 14.99,
      image: '/images/prod1.jpg',
      stock: 150,
    },
    {
      _id: '2',
      name: 'Lemony Lemonade',
      slug: 'lemony-lemonade',
      category: 'Drinks',
      origin: 'Italy',
      occasion: ['dessert', 'fruit', 'smoothies', 'icecream'],
      price: 1.99,
      image: '/images/prod2.jpg',
      stock: 0,
    },
    {
      _id: '3',
      name: 'Bio Red Berries Cake',
      slug: 'bio-red-berries-cake',
      category: 'Pastries',
      origin: 'Italy',
      occasion: ['dessert', 'fruit', 'smoothies', 'icecream'],
      price: 4.99,
      image: '/images/prod3.jpg',
      stock: 15,
    },
    {
      _id: '4',
      name: 'Vegan Granola',
      slug: 'vegan-granola',
      category: 'Cereals',
      origin: 'Italy',
      occasion: ['dessert', 'fruit', 'smoothies', 'icecream'],
      price: 1.99,
      image: '/images/prod4.jpg',
      stock: 5,
    },
  ],
};

export default data;
